Topic sk jcs more fss fixes (#115)
* more fss fixes for AD specific subnet.

* Revert "more fss fixes for AD specific subnet."

This reverts commit 2f5e48d6b8b8c1645e61478e20f4e52785e870bf.

* More fixes for fss/MT.
Remove subnet id for existing mt and existing fss
Remove subnet cidr for existing mt and existing fss
Fix AD ui screen.

* terraform fmt
14c schema.yaml fix.

* Fix AD issue with FSS

* JCS-13511 - Improvements to existing FSS use case

* tf format.

* Fixed issue with new FSS

* Fixed issue with new FSS

* Topic sk jcs mt vcn check (#112)

* Check if the mount target is is from the same vcn as network vcn.

* terraform fmt.

* incorporated Roberto's comments.

* terraform fmt.

* FIx the datasources.

* tf fmt.

* Fix the non fss issue.

* terraform fmt.

Co-authored-by: Abhijit Paranjpe <abhijit.paranjape@oracle.com>

diff --git a/terraform/modules/compute/wls_compute/userdata/bootstrap b/terraform/modules/compute/wls_compute/userdata/bootstrap
--- a/terraform/modules/compute/wls_compute/userdata/bootstrap
+++ b/terraform/modules/compute/wls_compute/userdata/bootstrap
@@ -149,6 +149,21 @@ if [ "$add_fss" == "true" ]; then
   mount_path=$(sudo su oracle -c 'python3 /opt/scripts/databag.py mount_path')
   export_path=$(sudo su oracle -c 'python3 /opt/scripts/databag.py export_path')
 
+  wls_existing_vcn_id=$(sudo su oracle -c 'python3 /opt/scripts/databag.py wls_existing_vcn_id')
+  mount_vcn_id=$(sudo su oracle -c 'python3 /opt/scripts/databag.py mount_vcn_id')
+
+  if [ $mount_vcn_id != "" ]; then
+    echo "Checking if the mount target and the WebLogic servers are in the same VCN" | log >> $log_file
+    if [ "$wls_existing_vcn_id" == "$mount_vcn_id" ]; then
+      echo "The mount target and the WebLogic servers are in the same VCN [$wls_existing_vcn_id]" | log >> $log_file
+    else
+      echo "The mount target is not in the same VCN as the WebLogic servers [$wls_existing_vcn_id, $mount_vcn_id]. Exiting" | log >> $log_file
+      #clean up script
+      /opt/scripts/tidyup.sh
+      exit 1
+    fi
+  fi
+
   echo "Executing fss mounting script" | log >> $log_file
   output=$(/opt/scripts/fss_mount.sh -i $mount_ip -p $mount_path -e $export_path 2>&1)
   exit_code=$?
